import json
import os
from typing import Dict

INVALID_SUBREDDITS = set([
  "1btcxairdrop",
  "@weblock",
  "adshares",
  "aidusofficial",
  "akropolisio",
  "aladiex",
  "aliumswap_official",
  "alphacat_io",
  "arawtoken",
  "armtoken",
  "autonio",
  "avccoin",
  "babyshib_com",
  "bbscoin",
  "betprotocol",
  "bezant",
  "bigdatacash",
  "binance_smart_chain_girl_bscgirl_listed_on",
  "bintexfutures",
  "biotron",
  "bitceo_io",
  "bitcicom",
  "bitcoin-diamond",
  "bitcoinhedge",
  "bitcoinzeroofficial",
  "bitmax",
  "bitonyx_official",
  "bitpayerdex",
  "bitrewards_official",
  "bityuan",
  "boscoin",
  "boxla888",
  "brainautdefi",
  "bsy_bestay",
  "btcnetworkofficial",
  "bulleon",
  "bytenext",
  "ccntoken",
  "centerprime",
  "ceur_is_now_officially_live_on_mainnet",
  "citizenfinance",
  "connectxon",
  "counosplatform",
  "crad",
  "crypto_rocketeer",
  "curioinvest",
  "daretoken",
  "davnetwork",
  "dctoinfo",
  "decentralizedml",
  "defiforyou",
  "dent",
  "dfuture_finance",
  "dmex_finance",
  "doggyswap",
  "domraider",
  "dragonbiteofficial",
  "dumpdoge_1st_of_its_kind_tokenomics_that_will",
  "dxdao",
  "ecosc",
  "edc_blockchain",
  "ejectelonofficial",
  "electrumdarktoken",
  "escoinico",
  "etg_finance",
  "ethbox",
  "ethereum-pro",
  "etherflyerexchange",
  "ethermon_io",
  "eurocoinpay",
  "everus",
  "everycoinico",
  "everyonescrypto",
  "exclusivecoin",
  "eyfi_finance",
  "falcon_sbs-2020",
  "fedoragold",
  "finswap",
  "fiolanetwork",
  "fireinutoken",
  "forestinghq",
  "fortysevenbank",
  "futurexcrypto",
  "fyeth_finance",
  "galaxiumspace",
  "gen_token",
  "genius-coin",
  "giantadmin",
  "gifto",
  "goaltimen",
  "goesuphigher",
  "golduck7",
  "hasanahetc",
  "hashbridge_oracle",
  "hashbxglobal",
  "hashgard",
  "hnb_eco",
  "hogl",
  "hyperchain_community",
  "hypermeteor",
  "introducing_zwap_zilswaps_governance_token",
  "ioox-system",
  "iouico",
  "jewelpay",
  "jivizcoin",
  "join_phoenix_force_to_moonshot_immortality_brand",
  "karmaeos",
  "kenuinu",
  "koloopbabic",
  "kp2rnetwork",
  "kwhcoin",
  "laikacoin",
  "largocoin",
  "lendingblock",
  "levelgnet",
  "lightcoinex",
  "liquid",
  "liquidapps",
  "livenpay",
  "loaprotocol",
  "lovecoinreddit",
  "lpntokenproo",
  "lympo",
  "mamadogecoin",
  "martiandao",
  "matrexcoin",
  "mayapreferred223",
  "mdsquare",
  "melalienetwork",
  "mercicoin",
  "merebelproject",
  "meridiannetwork",
  "merlinlab",
  "mgp_esports_token_no_memecoin_no_shitcoin_real",
  "mmon-defi",
  "mncio",
  "modihost",
  "monerovofficial",
  "moneyplanttoken",
  "moondayplus",
  "moonpad_oa",
  "mtt-coin",
  "naftytoken",
  "narrativenetwork",
  "neftipedia",
  "neoworldtech",
  "nervenetwork",
  "new",
  "nfxservice",
  "nitroexchange",
  "nydronia_2021",
  "oduwacoin",
  "officialixinium",
  "olxacoin",
  "omegadefi",
  "omnitude",
  "oracle_chain",
  "oreodefiofficial",
  "origonetwork",
  "otocash",
  "pandafinance",
  "paytomat",
  "peepcoinproject",
  "phoenixdefifinance",
  "phoenixprotocol",
  "pocblockchain",
  "polispay",
  "porkswapfinance_take_a_look_this_gonna_be_huge",
  "prizm-space",
  "pryztoken%20",
  "quish_coin",
  "rate3",
  "redfox_labs",
  "release8",
  "richierichbsc",
  "rigelfinance",
  "rifos",
  "rivetz",
  "robbinhoods_antiwhales_system_rewards_busd_to",
  "rubycoin",
  "safemooncashcommunity",
  "savethekidsbsc",
  "scorum",
  "secretsky.finance",
  "shabu-shabu-finance",
  "sharder",
  "siriustoken",
  "sleepyslothfinance",
  "somesingssx",
  "sparkster_me",
  "spectresecuritycoin",
  "spectrumspt",
  "spock_chain",
  "stakinglab",
  "starkchainofficial",
  "stellar_gold",
  "stktoken",
  "streamityofficial",
  "submit",
  "swapcoinz",
  "syncfab",
  "synergycoin",
  "tardigrades_finance_trdg",
  "tatatoken",
  "tecraspace",
  "telosnetwork",
  "tenx",
  "the-astra-coin",
  "themisoracle",
  "thephoenixtoken",
  "thorecoin",
  "tilwiki_official",
  "timecoin_protocol",
  "titanprojects",
  "token_cashpay_tcp",
  "tokenbacon",
  "tronipay",
  "ttcrypto_info",
  "uchain",
  "ultrainchain",
  "uniswapfinance",
  "usdxwallet",
  "vdice",
  "vegawallet",
  "versoview",
  "viagratoken",
  "vodix",
  "wgreenpay",
  "windswap",
  "wppcoin",
  "xanalianft",
  "xiglute_coin_utility_token_social",
  "xxxnifty.com",
  "ybearreddit",
  "yfdfi",
  "ylandfinance",
  "ystarpro",
  "zebidata",
  "zillatoken"
])

def get_subreddit_rank() -> Dict[str, int]:
  info_file = f'{os.path.expanduser("~")}/github/soulmachine/coinmarketcap-crawler/data/cryptocurrency-info-2021-07-19.json'
  with open(info_file, 'rt') as f:
    data = json.load(f)
    l = [(x['subreddit'].strip('/').lower(), i) for i, x in enumerate(data['data'].values())]
    l = [x for x in l if x]
    l = [x for x in l if x[0] not in INVALID_SUBREDDITS and not x[0].startswith('?utm_')]
    return dict(l)

if __name__ == "__main__":
  with open('../config.json', 'rt') as f:
    subreddits = set(json.loads(f.read()))
  subreddit_rank = get_subreddit_rank()
  # for name, rank in subreddit_rank.items():
  #   if name not in subreddits:
  #     print(name)
  # exit(0)
  subreddits.update(subreddit_rank.keys())
  subreddits = list(subreddits)
  subreddits = sorted(subreddits)
  # subreddits = sorted(subreddits, key=lambda name: subreddit_rank.get(name, -1))
  with open('../config.json', 'wt') as f:
    f.write(json.dumps(subreddits, indent=2))
